In [33]:
import numpy as np

## Task1

In [34]:
a = np.matrix([[2,1,1,10],
             [3,2,3,18],
             [1,4,9,16]])
print(a)

[[ 2  1  1 10]
 [ 3  2  3 18]
 [ 1  4  9 16]]


In [35]:
# 1x3 = eq4
eq4 = a[0] * 3

In [36]:
a = np.append(a,eq4,axis=0)

In [37]:
#eq4-eq2 =  eq5
eq5 = eq4-a[1]

In [38]:
a = np.append(a,eq5,axis=0)

In [39]:
#ep4x3 = eq6
eq6 = a[3] * 3

In [40]:
a = np.append(a,eq6,axis=0)

In [41]:
#eq6 - eq3 = eq7
eq7 = a[5] - a[2]

In [42]:
a = np.append(a,eq7,axis=0)

In [43]:
#ep7 - ep5x5 = x
x = a[6] - a[4]*5

In [44]:
x

matrix([[ 2,  0,  0, 14]])

In [45]:
# get x
x = x/2

In [46]:
result = x.copy()

In [47]:
result

matrix([[1., 0., 0., 7.]])

In [48]:
# get y = eq5 - x*3 
y = a[4] - x*3

In [49]:
result = np.append(result,y,axis=0)

In [50]:
result

matrix([[ 1.,  0.,  0.,  7.],
        [ 0.,  1.,  0., -9.]])

In [51]:
z = a[2] - x - (y*4)

In [52]:
z /= 9

In [53]:
result = np.append(result,z,axis=0)

In [54]:
result

matrix([[ 1.,  0.,  0.,  7.],
        [ 0.,  1.,  0., -9.],
        [ 0.,  0.,  1.,  5.]])

## Task2

In [55]:
a = np.matrix([[2,1,1],
             [3,2,3],
             [1,4,9]])
b = np.matrix([[10],[18],[16]])

In [56]:
# x = A^-1 B
x = np.linalg.inv(a).dot(b)

In [57]:
x

matrix([[ 7.],
        [-9.],
        [ 5.]])

In [58]:
m = np.matrix([[2,-5],
               [3,1]])
n = np.matrix([[15],[31]])
a = np.matrix([[2,1,1],
             [3,2,3],
             [1,4,9]])
b = np.matrix([[10],[18],[16]])
j = np.matrix([ [1,2,1,1],
                [2,0,4,3],
                [4,2,2,1],
                [-3,1,3,2]
                ])
l = np.matrix([ [13],[28],[20],[6]])

## Task3

In [59]:
def fwd_elim(Ab):
    Ab_re = Ab.copy()
    [nr,nc] = Ab_re.shape
    
    # set i as the Iteration index
    for i in range(1,nr):
        print('Iteration #{}: '.format(i))
        # set r as the row index to work on
        for r in range(i,nr):
            print('  working on row index {}'.format(r))
            # iteration index represent the order of the variable that we want to eliminate
            row_factor = Ab_re[r,i-1]/Ab_re[i-1,i-1]
            Ab_re[r,:] = Ab_re[r,:] - Ab_re[i-1,:]*row_factor
        #end for r
    #end for i
    print(Ab_re)
    return Ab_re

In [60]:
def backsub(Ab_re):
    [nr,nc] = Ab_re.shape
    x = np.empty(nr)
    
    x[nr-1] = Ab_re[nr-1,nc-1]/Ab_re[nr-1,nr-1]
    print('x[{}] = {}'.format(nr-1,x[nr-1]))
    
    for r in range(nr-2,-1,-1):
        # range (1,-1,-1) will give i = 1,0
        # sum_of_products = sum of products of coeff of x[i+1] and x[i+1]
        # before this
        sum_of_products = 0
        for c in range(r+1, nr):
            product = Ab_re[r,c]*x[c]
            sum_of_products = sum_of_products + product
        #end for
        # -,- = + 
        # -,+ = -
        x[r] = (Ab_re[r,nc-1] - sum_of_products)/Ab_re[r,r]
    #end for
    return x
#end function
    

In [61]:
ab = np.append(a,b,axis=1)

In [62]:
ab = ab*1.0

In [63]:
ab_re = fwd_elim(ab)

Iteration #1: 
  working on row index 1
  working on row index 2
Iteration #2: 
  working on row index 2
[[  2.    1.    1.   10. ]
 [  0.    0.5   1.5   3. ]
 [  0.    0.   -2.  -10. ]]


In [64]:
backsub(ab_re)

x[2] = 5.0


array([ 7., -9.,  5.])

In [65]:
mn = np.append(m,n,axis=1)
mn *= 1.0

In [66]:
mn_re = fwd_elim(mn)

Iteration #1: 
  working on row index 1
[[ 2 -5 15]
 [ 0  8  8]]


In [67]:
backsub(mn_re)

x[1] = 1.0


array([10.,  1.])

In [68]:
jl = np.append(j,l,axis=1)
jl *= 1.0

In [69]:
jl_re = fwd_elim(jl)

Iteration #1: 
  working on row index 1
  working on row index 2
  working on row index 3
Iteration #2: 
  working on row index 2
  working on row index 3
Iteration #3: 
  working on row index 3
[[  1   2   1   1  13]
 [  0  -4   2   1   2]
 [  0   0  -5  -4 -35]
 [  0   0   0  -1 -15]]


In [70]:
backsub(jl_re)

x[3] = 15.0


array([ 1.5 ,  0.75, -5.  , 15.  ])

## Task4

In [71]:
def Cramer_rule(A,B):
    size = A.shape
    ans = np.empty(size[0])
    for i in range(size[0]):
        ax = A.copy()
        ax[:,i] = B
        ans[i] = np.linalg.det(ax)/np.linalg.det(A)
    print(ans) 

In [72]:
Cramer_rule(m,n)

[10.  1.]


In [73]:
Cramer_rule(a,b)

[ 7. -9.  5.]


In [74]:
Cramer_rule(j,l)

[ 3.  1. -2. 10.]


## Task5

In [77]:
m = np.matrix([[3,1],
               [2,-5]
               ])
n = np.matrix([[31],[15]])
a = np.matrix([[3,2,3],
               [2,1,1],
               [1,4,9]])
b = np.matrix([[18],[10],[16]])
j = np.matrix([ [4,2,2,1],
                [2,0,4,3],
                [1,2,1,1],
                [-3,1,3,2]
                ])
l = np.matrix([ [20],[28],[13],[6]])

In [78]:
mn = np.append(m,n,axis=1)


In [79]:
mn_re = fwd_elim(mn)

Iteration #1: 
  working on row index 1
[[ 3  1 31]
 [ 0 -5 -5]]


In [80]:
backsub(mn_re)

x[1] = 1.0


array([10.,  1.])

In [81]:
ab = np.append(a,b,axis=1)

In [84]:
ab

matrix([[ 3,  2,  3, 18],
        [ 2,  1,  1, 10],
        [ 1,  4,  9, 16]])

In [85]:
ab_re = fwd_elim(ab*1.0)

Iteration #1: 
  working on row index 1
  working on row index 2
Iteration #2: 
  working on row index 2
[[ 3.00000000e+00  2.00000000e+00  3.00000000e+00  1.80000000e+01]
 [ 0.00000000e+00 -3.33333333e-01 -1.00000000e+00 -2.00000000e+00]
 [ 0.00000000e+00 -4.44089210e-16 -2.00000000e+00 -1.00000000e+01]]


In [86]:
backsub(ab_re)

x[2] = 4.999999999999995


array([ 7., -9.,  5.])

In [87]:
jl =np.append(j,l,axis=1)

In [88]:
jl

matrix([[ 4,  2,  2,  1, 20],
        [ 2,  0,  4,  3, 28],
        [ 1,  2,  1,  1, 13],
        [-3,  1,  3,  2,  6]])

In [91]:
jl_re = fwd_elim(jl*1.0)

Iteration #1: 
  working on row index 1
  working on row index 2
  working on row index 3
Iteration #2: 
  working on row index 2
  working on row index 3
Iteration #3: 
  working on row index 3
[[  4.    2.    2.    1.   20. ]
 [  0.   -1.    3.    2.5  18. ]
 [  0.    0.    5.    4.5  35. ]
 [  0.    0.    0.   -1.8 -18. ]]


In [92]:
backsub(jl_re)

x[3] = 10.000000000000005


array([ 3.,  1., -2., 10.])